//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.Friendly.Store.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.Friendly.Store.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///対象アプリケーションが通信不能な状態になったか、
        ///シリアライズ不可能な型のデータを転送しようとした可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppCommunication {
            get {
                return ResourceManager.GetString("ErrorAppCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///対象アプリケーションが通信不能な状態になったか、
        ///シリアライズ不可能な型のデータを転送しようとした可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppCommunication1 {
            get {
                return ResourceManager.GetString("ErrorAppCommunication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppConnection {
            get {
                return ResourceManager.GetString("ErrorAppConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppConnection1 {
            get {
                return ResourceManager.GetString("ErrorAppConnection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [型 : {0}][操作 : {1}({2})]
        ///同名の操作が見つかりましたが、操作を実行できませんでした。
        ///引数指定が間違っている可能性があります。
        ///数値型、Enumも厳密に判定されるのでご注意お願いします。
        ///(例として、long型の引数にint型を渡しても別の型と判断され、解決に失敗します。)
        ///また、params付きの配列の場合は、その型の配列に格納して渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArgumentInvokeFormat {
            get {
                return ResourceManager.GetString("ErrorArgumentInvokeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [型 : {0}][操作 : {1}({2})]
        ///同名の操作が見つかりましたが、操作を実行できませんでした。
        ///引数指定が間違っている可能性があります。
        ///params付きの配列の場合は、その型の配列に格納して渡してください。
        ///また、object[] の場合 params object[]と区別がつかず、分解されて引数に渡されます。
        ///そのため、object[]の要素にobject[]を入れて引き渡してください。
        ///object[] arg;//引き渡したいobject[]
        ///object[] tmpArg = new object[0];
        ///tmpArg[0] = arg;//これを引き渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArgumentInvokeFormatForObjectArray {
            get {
                return ResourceManager.GetString("ErrorArgumentInvokeFormatForObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに実行されています。Asyncクラスの実行は一度だけです。複数回呼び出す場合は、再度Asyncクラスを生成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAsyncDuplicativeCall {
            get {
                return ResourceManager.GetString("ErrorAsyncDuplicativeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するファイルが不正な状態で、かつ削除に失敗しました。
        ///以下のファイルを手動で削除してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBinaryInstall {
            get {
                return ResourceManager.GetString("ErrorBinaryInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のプロセスとの接続に失敗しました。
        ///CLRのバージョンの指定が不正な可能性があります。
        ///CLRのバージョンは.NetFrameworkのバージョンと異なる場合があるのでご注意願います。
        ///サポートされているバージョンはCodeerのWebサイトを参照お願いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCLR {
            get {
                return ResourceManager.GetString("ErrorCLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}引数が不正です。
        ///「ネームスペース」もしくは「クラス名称」と推測されます。引数を生成した構文を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDefinitionArgument {
            get {
                return ResourceManager.GetString("ErrorDefinitionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}引数が不正です。
        ///引数に使用されたAppVarの中に、異なるAppFriendの管理する変数プールに属するAppVarがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDifferentAppFriendVar {
            get {
                return ResourceManager.GetString("ErrorDifferentAppFriendVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に破棄されたオブジェクトです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDisposedObject {
            get {
                return ResourceManager.GetString("ErrorDisposedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のプロセスとの接続に失敗しました。
        ///インストールに失敗している可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDllLoad {
            get {
                return ResourceManager.GetString("ErrorDllLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のプロセスとの接続に失敗しました。
        ///インストールに失敗している可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDllLoad1 {
            get {
                return ResourceManager.GetString("ErrorDllLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///指定の実行対象スレッドに含まれるウィンドウは存在しません。
        ///もしくは既に破棄されました。
        ///スプラッシュウィンドウを表示するアプリケーションの場合は、起動直後にメインウィンドウがスプラッシュウィンドウになっている場合があります。
        ///明示的に期待のウィンドウのハンドルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorExecuteThreadWindowHandle {
            get {
                return ResourceManager.GetString("ErrorExecuteThreadWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///指定の実行対象スレッドに含まれるウィンドウは存在しません。
        ///もしくは既に破棄されました。
        ///スプラッシュウィンドウを表示するアプリケーションの場合は、起動直後にメインウィンドウがスプラッシュウィンドウになっている場合があります。
        ///明示的に期待のウィンドウのハンドルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorExecuteThreadWindowHandle1 {
            get {
                return ResourceManager.GetString("ErrorExecuteThreadWindowHandle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProgramDataフォルダ以下への書き込み権限がないことが考えられます。
        ///Codeer.Friendlyは初期実行時にProgramData/Codeer.Friendlyフォルダとそれ以下にいくつかのファイルを作成します。テストプロジェクトにこのフォルダへの書き込み権限を与えてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFriendlySystem {
            get {
                return ResourceManager.GetString("ErrorFriendlySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な終了指定です。通常このメソッドは使用しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidCompleted {
            get {
                return ResourceManager.GetString("ErrorInvalidCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なstatic呼び出しです。操作情報には型が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidStaticCall {
            get {
                return ResourceManager.GetString("ErrorInvalidStaticCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬスレッドからの呼び出しがありました。
        ///起点となるWindowsAppFriendを生成したスレッドからのみ、呼び出し可能です。
        ///必要であれば、スレッドごとにWindowsAppFriendを生成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidThreadCall {
            get {
                return ResourceManager.GetString("ErrorInvalidThreadCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬスレッドからの呼び出しがありました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidThreadCall1 {
            get {
                return ResourceManager.GetString("ErrorInvalidThreadCall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [new {0}({1})]
        ///指定の引数で実行できる可能性のあるコンストラクタが複数発見されました。
        ///引数に引き渡す型を明確にするか、もしくはOperationTypeInfoを使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorManyFoundConstractorFormat {
            get {
                return ResourceManager.GetString("ErrorManyFoundConstractorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [型 : {0}][操作 : {1}({2})]
        ///指定の引数で実行できる可能性のある操作が複数発見されました。
        ///引数に引き渡す型を明確にするか、もしくはOperationTypeInfoを使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorManyFoundInvokeFormat {
            get {
                return ResourceManager.GetString("ErrorManyFoundInvokeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [new {0}({1})]
        ///コンストラクタが見つかりませんでした。
        ///引数指定が間違っている可能性があります。
        ///数値型、Enumも厳密に判定されるのでご注意お願いします。
        ///(例として、long型の引数にint型を渡しても別の型と判断され、解決に失敗します。)
        ///また、params付きの配列の場合は、その型の配列に格納して渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotFoundConstractorFormat {
            get {
                return ResourceManager.GetString("ErrorNotFoundConstractorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [new {0}({1})]
        ///コンストラクタが見つかりませんでした。
        ///引数指定が間違っている可能性があります。
        ///params付きの配列の場合は、その型の配列に格納して渡してください。
        ///また、object[] の場合 params object[]と区別がつかず、分解されて引数に渡されます。
        ///そのため、object[]の要素にobject[]を入れて引き渡してください。
        ///object[] arg;//引き渡したいobject[]
        ///object[] tmpArg = new object[0];
        ///tmpArg[0] = arg;//これを引き渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotFoundConstractorFormatForObjectArray {
            get {
                return ResourceManager.GetString("ErrorNotFoundConstractorFormatForObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [型 : {0}][操作 : {1}({2})]
        ///指定の操作が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotFoundInvokeFormat {
            get {
                return ResourceManager.GetString("ErrorNotFoundInvokeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OperationTypeInfo.Arguments : ({0})][引数 : ({1})]
        ///操作型情報の引数指定が不正です。実際に引き渡している引数の数と型指定の数が一致しません。
        ///params付きの配列の場合は、その型の配列に格納して渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOperationTypeArgInfoFormat {
            get {
                return ResourceManager.GetString("ErrorOperationTypeArgInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OperationTypeInfo.Arguments : ({0})][引数 : ({1})]
        ///操作型情報の引数指定が不正です。実際に引き渡している引数の数と型指定の数が一致しません。
        ///params付きの配列の場合は、その型の配列に格納して渡してください。
        ///また、object[] の場合 params object[]と区別がつかず、分解されて引数に渡されます。
        ///そのため、object[]の要素にobject[]を入れて引き渡してください。
        ///object[] arg;//引き渡したいobject[]
        ///object[] tmpArg = new object[0];
        ///tmpArg[0] = arg;//これを引き渡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorOperationTypeArgInfoForObjectArrayFormat {
            get {
                return ResourceManager.GetString("ErrorOperationTypeArgInfoForObjectArrayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロセスの操作に失敗しました。対象プロセスを操作する権限が足りていないか、接続中に終了した可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessAcess {
            get {
                return ResourceManager.GetString("ErrorProcessAcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロセスの操作に失敗しました。
        ///以下の可能性が考えられます。
        ///・CLRのバージョン指定が間違っている。
        ///・対象プロセスを操作する権限が足りていない。
        ///・接続中に対象プロセスが終了した。
        ///・指定のウィンドウハンドルのウィンドウが破棄された。
        ///スプラッシュウィンドウを表示するアプリケーションの場合は、起動直後にメインウィンドウがスプラッシュウィンドウになっている場合があります。
        ///明示的に期待のウィンドウのハンドルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessAcess1 {
            get {
                return ResourceManager.GetString("ErrorProcessAcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロセスを操作する権限が足りていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessOperation {
            get {
                return ResourceManager.GetString("ErrorProcessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラットフォームターゲットがテスト対象とテストプロセスで異なります。合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTargetCpuDifference {
            get {
                return ResourceManager.GetString("ErrorTargetCpuDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラットフォームターゲットがテスト対象とテストプロセスで異なります。合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTargetCpuDifference1 {
            get {
                return ResourceManager.GetString("ErrorTargetCpuDifference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLRのバージョンが予測できません。
        ///対象アプリ内に複数のCLRがロードされている可能性があります。
        ///対象のCLRのバージョンを明示するコンストラクタを使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnpredicatableClrVersion {
            get {
                return ResourceManager.GetString("ErrorUnpredicatableClrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象アプリケーション内部で例外が発生しました。
        ///[メッセージ]
        ///{0}
        ///[例外タイプ]
        ///{1}
        ///[エラーの原因]
        ///{2}
        ///[スタックトレース]
        ///{3}
        ///[ヘルプ]
        ///{4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionInfoFormat {
            get {
                return ResourceManager.GetString("ExceptionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定の変数はIEnumerableを実装していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HasNotEnumerable {
            get {
                return ResourceManager.GetString("HasNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AppVarの中身がnullのオブジェクトに対して操作を呼び出しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NullObjectOperation {
            get {
                return ResourceManager.GetString("NullObjectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLRバージョン文字列を置き換えました。
        ///{0} -&gt; {1}
        ///指定の文字列は現在非推奨です。
        ///置き換え後の文字列(CLRの正式バージョン文字列)を使用するか、
        ///CLRのバージョンを指定しないコンストラクタを使ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObsoleteClrOrder {
            get {
                return ResourceManager.GetString("ObsoleteClrOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同時通信数の上限に達しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfCommunicationNo {
            get {
                return ResourceManager.GetString("OutOfCommunicationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同時通信数の上限に達しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfCommunicationNo1 {
            get {
                return ResourceManager.GetString("OutOfCommunicationNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション内部で使用できる変数領域を使い切りました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}]
        ///指定の型が見つかりません。
        ///型フルネームが間違っているか、指定の型を含むモジュールが、まだロードされていない可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownTypeInfoFormat {
            get {
                return ResourceManager.GetString("UnknownTypeInfoFormat", resourceCulture);
            }
        }
    }
}
