//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.Friendly.Store.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.Friendly.Store.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///対象アプリケーションが通信不能な状態になったか、
        ///シリアライズ不可能な型のデータを転送しようとした可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppCommunication {
            get {
                return ResourceManager.GetString("ErrorAppCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppConnection {
            get {
                return ResourceManager.GetString("ErrorAppConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のプロセスとの接続に失敗しました。
        ///CLRのバージョンの指定が不正な可能性があります。
        ///CLRのバージョンは.NetFrameworkのバージョンと異なる場合があるのでご注意願います。
        ///サポートされているバージョンはCodeerのWebサイトを参照お願いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCLR {
            get {
                return ResourceManager.GetString("ErrorCLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のプロセスとの接続に失敗しました。
        ///インストールに失敗している可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDllLoad {
            get {
                return ResourceManager.GetString("ErrorDllLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションとの通信に失敗しました。
        ///指定の実行対象スレッドに含まれるウィンドウは存在しません。
        ///もしくは既に破棄されました。
        ///スプラッシュウィンドウを表示するアプリケーションの場合は、起動直後にメインウィンドウがスプラッシュウィンドウになっている場合があります。
        ///明示的に期待のウィンドウのハンドルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorExecuteThreadWindowHandle {
            get {
                return ResourceManager.GetString("ErrorExecuteThreadWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬスレッドからの呼び出しがありました。
        ///起点となるWindowsAppFriendを生成したスレッドからのみ、呼び出し可能です。
        ///必要であれば、スレッドごとにWindowsAppFriendを生成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidThreadCall {
            get {
                return ResourceManager.GetString("ErrorInvalidThreadCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロセスの操作に失敗しました。対象プロセスを操作する権限が足りていないか、接続中に終了した可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProcessAcess {
            get {
                return ResourceManager.GetString("ErrorProcessAcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラットフォームターゲットがテスト対象とテストプロセスで異なります。合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTargetCpuDifference {
            get {
                return ResourceManager.GetString("ErrorTargetCpuDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同時通信数の上限に達しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfCommunicationNo {
            get {
                return ResourceManager.GetString("OutOfCommunicationNo", resourceCulture);
            }
        }
    }
}
